#!/usr/bin/env node
// Generate and validate SoftFloat golden-vector tests.
//
// This single entry point intentionally owns the whole golden-vector workflow:
//   - `core` builds the small representative fixture set and direct tests.
//   - `sweep` builds edge/random/exhaustive fixture files and digest tests.
//   - `packages` turns committed fixture files into sweep_test/batch<N> packages.
//   - `check` replays committed fixture files against the C oracle binaries.
//   - `all` refreshes core + sweep + generated MoonBit packages.
//
// Keeping these pieces together matters because the fixture metadata, LCG
// sequence, digest fold, and MoonBit emitters must stay in lockstep. If one
// part changes without the others, the generated sweep packages can silently
// test a different input stream from the one stored under tools/vectors.

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const SCRIPT_PATH = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(SCRIPT_PATH), "..");
const TOOL_DIR = path.join(ROOT, "tools");
const VECTOR_DIR = path.join(TOOL_DIR, "vectors");
const TEST_ROOT = path.join(ROOT, "sweep_test");
const CORE_VECTOR_PATH = path.join(VECTOR_DIR, "core.txt");
const CORE_TEST_PATH = path.join(ROOT, "golden_core_wbtest.mbt");
const SWEEP_TEST_PATH = path.join(ROOT, "golden_sweep_digest_wbtest.mbt");
const BUILD = path.join(TOOL_DIR, "build.sh");
const GENERATED_HEADER = "// Generated by tools/test_gen.mjs; do not edit by hand.";

// Each generated package gets one helper file plus up to nine vector files.
// That preserves the requested layout: 10 files per batch package and at most
// 100 MoonBit `test` blocks per vector file.
const FILES_PER_BATCH = 10;
const TESTS_PER_FILE = 100;
const VECTOR_FILES_PER_BATCH = FILES_PER_BATCH - 1;
const TESTS_PER_BATCH = VECTOR_FILES_PER_BATCH * TESTS_PER_FILE;

// Sweep fixtures can be very large. The generated batch packages therefore
// check 200-record digest chunks instead of embedding millions of direct
// assertions. Smaller direct tests are still emitted for core/smoke fixtures.
const DIGEST_CHUNK_SIZE = 200;

// Deterministic 64-bit LCG and FNV-style digest constants. BigInt is used here
// because JavaScript Numbers cannot represent all 64-bit bit patterns exactly.
const SEED = 0x5F0F7A7Cn;
const HASH_INIT = 0xCBF29CE484222325n;
const HASH_PRIME = 0x100000001B3n;
const MASK64 = (1n << 64n) - 1n;
const LCG_MULT = 0x5851F42D4C957F2Dn;
const LCG_INC = 0x14057B7EF767814Fn;

const SPECS = ["x86_8086_sse", "riscv"];
const ROUNDINGS = ["near_even", "min", "max", "odd"];
const ALL_ROUNDINGS = ["near_even", "min_mag", "min", "max", "near_max_mag", "odd"];
const TININESS = ["after", "before"];
const FORMATS = {
  f16: [16, 4],
  f32: [32, 8],
  f64: [64, 16],
};
const ORACLES = {
  x86_8086_sse: path.join(TOOL_DIR, "oracle-8086-sse"),
  riscv: path.join(TOOL_DIR, "oracle-riscv"),
};

const EDGE_VALUES = {
  f16: [
    "0000", "8000", "0001", "03FF", "0400", "7BFF",
    "3C00", "BC00", "4000", "3800", "7C00", "FC00",
    "7E00", "FE00", "7C01", "FC01", "7D55", "FD55",
  ],
  f32: [
    "00000000", "80000000", "00000001", "007FFFFF", "00800000", "7F7FFFFF",
    "3F800000", "BF800000", "40000000", "3F000000", "7F800000", "FF800000",
    "7FC00000", "FFC00000", "7F800001", "FF800001", "7FAAAAAA", "FFA00001",
  ],
  f64: [
    "0000000000000000", "8000000000000000", "0000000000000001", "000FFFFFFFFFFFFF",
    "0010000000000000", "7FEFFFFFFFFFFFFF", "3FF0000000000000", "BFF0000000000000",
    "4000000000000000", "3FE0000000000000", "7FF0000000000000", "FFF0000000000000",
    "7FF8000000000000", "FFF8000000000000", "7FF0000000000001", "FFF0000000000001",
    "7FFAAAAAAAAAAAAA", "FFF0000000001234",
  ],
};

const INTEGER_INPUTS = {
  ui32: ["00000000", "00000001", "00000002", "0000FFFF", "7FFFFFFF", "80000000", "FFFFFFFF"],
  i32: ["00000000", "00000001", "FFFFFFFF", "7FFFFFFF", "80000000", "80000001"],
  ui64: [
    "0000000000000000", "0000000000000001", "00000000FFFFFFFF", "0000000100000000",
    "7FFFFFFFFFFFFFFF", "8000000000000000", "FFFFFFFFFFFFFFFF",
  ],
  i64: [
    "0000000000000000", "0000000000000001", "FFFFFFFFFFFFFFFF",
    "7FFFFFFFFFFFFFFF", "8000000000000000", "8000000000000001",
  ],
};

const BINARY_OPS = {
  f16: ["f16_add", "f16_sub", "f16_mul", "f16_div", "f16_rem"],
  f32: ["f32_add", "f32_sub", "f32_mul", "f32_div", "f32_rem"],
  f64: ["f64_add", "f64_sub", "f64_mul", "f64_div", "f64_rem"],
};
const FMA_OPS = { f16: "f16_mul_add", f32: "f32_mul_add", f64: "f64_mul_add" };
const ROUND_TO_INT_OPS = { f16: "f16_round_to_int", f32: "f32_round_to_int", f64: "f64_round_to_int" };
const FLOAT_TO_INT_OPS = {
  f16: ["f16_to_ui32", "f16_to_ui64", "f16_to_i32", "f16_to_i64"],
  f32: ["f32_to_ui32", "f32_to_ui64", "f32_to_i32", "f32_to_i64"],
  f64: ["f64_to_ui32", "f64_to_ui64", "f64_to_i32", "f64_to_i64"],
};
const MIN_MAG_OPS = {
  f16: ["f16_to_ui32_min_mag", "f16_to_ui64_min_mag", "f16_to_i32_min_mag", "f16_to_i64_min_mag"],
  f32: ["f32_to_ui32_min_mag", "f32_to_ui64_min_mag", "f32_to_i32_min_mag", "f32_to_i64_min_mag"],
  f64: ["f64_to_ui32_min_mag", "f64_to_ui64_min_mag", "f64_to_i32_min_mag", "f64_to_i64_min_mag"],
};
const FLOAT_CONVERSION_OPS = {
  f16: ["f16_to_f32", "f16_to_f64"],
  f32: ["f32_to_bf16", "f32_to_f16", "f32_to_f64"],
  f64: ["f64_to_f16", "f64_to_f32"],
};
const INT_TO_FLOAT_OPS = [
  ["ui32", "ui32_to_f16"], ["ui32", "ui32_to_f32"], ["ui32", "ui32_to_f64"],
  ["ui64", "ui64_to_f16"], ["ui64", "ui64_to_f32"], ["ui64", "ui64_to_f64"],
  ["i32", "i32_to_f16"], ["i32", "i32_to_f32"], ["i32", "i32_to_f64"],
  ["i64", "i64_to_f16"], ["i64", "i64_to_f32"], ["i64", "i64_to_f64"],
];

const ROUNDING = {
  near_even: "@sf.RoundingMode::NearEven",
  min_mag: "@sf.RoundingMode::MinMag",
  min: "@sf.RoundingMode::Min",
  max: "@sf.RoundingMode::Max",
  near_max_mag: "@sf.RoundingMode::NearMaxMag",
  odd: "@sf.RoundingMode::Odd",
};
const TININESS_MODE = {
  after: "@sf.TininessMode::AfterRounding",
  before: "@sf.TininessMode::BeforeRounding",
};

const VARIANT_RE = /\b(NearMaxMag|NearEven|MinMag|Min|Max|Odd)\b/g;
const TININESS_RE = /\b(AfterRounding|BeforeRounding)\b/g;

class Lcg {
  constructor(state) {
    this.state = BigInt.asUintN(64, BigInt(state));
  }

  next() {
    this.state = (this.state * LCG_MULT + LCG_INC) & MASK64;
    return this.state;
  }
}

class DigestCase {
  constructor({ name, spec, op, source, digest }) {
    this.name = name;
    this.spec = spec;
    this.op = op;
    this.source = source;
    this.digest = digest;
  }
}

class GeneratedTest {
  constructor(helper, block) {
    this.helper = helper;
    this.block = block;
  }
}

class CoreCase {
  constructor(op, rounding, tininess, exact, inputs, inputKinds, outputKind) {
    this.op = op;
    this.rounding = rounding;
    this.tininess = tininess;
    this.exact = exact;
    this.inputs = inputs;
    this.inputKinds = inputKinds;
    this.outputKind = outputKind;
  }
}

const DIGEST_CASES = [];

function fail(message) {
  throw new Error(message);
}

function runCommand(args, options = {}) {
  const result = spawnSync(args[0], args.slice(1), {
    cwd: ROOT,
    encoding: "utf8",
    // Some validation groups contain hundreds of thousands of oracle records.
    // Node's default 1 MiB spawnSync buffer is too small for those batches,
    // while Python's subprocess path used an effectively larger pipe.
    maxBuffer: 512 * 1024 * 1024,
    ...options,
  });
  if (result.status !== 0) {
    const command = args.join(" ");
    const stderr = result.stderr ? `\n${result.stderr.trimEnd()}` : "";
    const stdout = result.stdout ? `\n${result.stdout.trimEnd()}` : "";
    fail(`command failed (${result.status ?? "signal"}): ${command}${stdout}${stderr}`);
  }
  return result;
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function exists(file) {
  return fs.existsSync(file);
}

function readText(file) {
  return fs.readFileSync(file, "utf8");
}

function writeText(file, text) {
  ensureDir(path.dirname(file));
  fs.writeFileSync(file, text);
}

function listVectorFiles() {
  if (!exists(VECTOR_DIR)) {
    return [];
  }
  return fs.readdirSync(VECTOR_DIR)
    .filter((name) => name.endsWith(".txt"))
    .sort()
    .map((name) => path.join(VECTOR_DIR, name));
}

function stem(file) {
  return path.basename(file, path.extname(file));
}

function hex(value, digits) {
  return BigInt.asUintN(64, BigInt(value)).toString(16).toUpperCase().padStart(digits, "0");
}

function hex64(value) {
  return hex(value, 16);
}

function parseHex(value) {
  return BigInt(`0x${value}`);
}

function ensureOracles() {
  if (Object.values(ORACLES).some((oracle) => !exists(oracle))) {
    runCommand([BUILD], { stdio: "inherit" });
  }
}

function oraclePath(spec) {
  return ORACLES[spec];
}

function cleanGeneratedSweepFixtures() {
  ensureDir(VECTOR_DIR);
  for (const file of listVectorFiles()) {
    const name = path.basename(file);
    if (name.startsWith("edge_") || name.startsWith("random_") || name.startsWith("exhaustive_")) {
      fs.unlinkSync(file);
    }
  }
  if (exists(SWEEP_TEST_PATH)) {
    fs.unlinkSync(SWEEP_TEST_PATH);
  }
}

function cartesianPairs(values) {
  const rows = [];
  for (const a of values) {
    for (const b of values) {
      rows.push([a, b]);
    }
  }
  return rows;
}

function bits(rng, fmt) {
  const [width, digits] = FORMATS[fmt];
  const mask = (1n << BigInt(width)) - 1n;
  return hex(rng.next() & mask, digits);
}

function modeCycle(index) {
  return [
    ROUNDINGS[index % ROUNDINGS.length],
    TININESS[Math.floor(index / ROUNDINGS.length) % TININESS.length],
    "1",
  ];
}

function allModeRows(inputs) {
  const rows = [];
  for (const rounding of ROUNDINGS) {
    for (const tininess of TININESS) {
      for (const values of inputs) {
        rows.push([rounding, tininess, "1", values]);
      }
    }
  }
  return rows;
}

function allRoundingRows(inputs) {
  const rows = [];
  for (const rounding of ALL_ROUNDINGS) {
    for (const exact of ["0", "1"]) {
      for (const values of inputs) {
        rows.push([rounding, "after", exact, values]);
      }
    }
  }
  return rows;
}

function cycledRandomRows(rng, fmt, arity, count) {
  const rows = [];
  for (let index = 0; index < count; index += 1) {
    const [rounding, tininess, exact] = modeCycle(index);
    const values = [];
    for (let item = 0; item < arity; item += 1) {
      values.push(bits(rng, fmt));
    }
    rows.push([rounding, tininess, exact, values]);
  }
  return rows;
}

function batchRecords(spec, op, rows) {
  // The C oracle supports a batch mode keyed by rounding/tininess/exact. Grouping
  // rows this way keeps generation fast while preserving the original row order.
  const groups = new Map();
  rows.forEach(([rounding, tininess, exact, inputs], index) => {
    const key = `${rounding}\0${tininess}\0${exact}`;
    if (!groups.has(key)) {
      groups.set(key, []);
    }
    groups.get(key).push([index, inputs]);
  });

  const records = Array(rows.length).fill(null);
  for (const key of [...groups.keys()].sort()) {
    const [rounding, tininess, exact] = key.split("\0");
    const batch = groups.get(key);
    const input = batch.map(([, inputs]) => inputs.join(" ")).join("\n") + "\n";
    const completed = runCommand(
      [oraclePath(spec), "--batch", op, rounding, tininess, exact],
      { input, captureOutput: true },
    );
    const actual = completed.stdout.split(/\r?\n/).filter((line) => line.length > 0);
    if (actual.length !== batch.length) {
      fail(`${op}/${spec}: oracle returned the wrong record count`);
    }
    batch.forEach(([index], offset) => {
      records[index] = actual[offset];
    });
  }
  return records.filter((record) => record !== null);
}

function mixDigest(value, digest) {
  return ((digest ^ (value & MASK64)) * HASH_PRIME) & MASK64;
}

function digestRecords(records) {
  // The digest deliberately folds only the oracle output and exception flags.
  // Inputs are reproduced by the generated MoonBit code; mismatched input order
  // changes the output stream and therefore the digest.
  let digest = HASH_INIT;
  for (const record of records) {
    const fields = record.split(/\s+/);
    digest = mixDigest(parseHex(fields.at(-2)), digest);
    digest = mixDigest(parseHex(fields.at(-1)), digest);
  }
  return digest;
}

function writeFixture(name, spec, op, rows, source) {
  const file = path.join(VECTOR_DIR, `${name}_${op}_${spec}.txt`);
  const records = batchRecords(spec, op, rows);
  writeText(file, records.join("\n") + "\n");
  DIGEST_CASES.push(new DigestCase({
    name: `${name}_${op}_${spec}`,
    spec,
    op,
    source,
    digest: digestRecords(records),
  }));
}

function edgeBinaryRows(fmt) {
  return allModeRows(cartesianPairs(EDGE_VALUES[fmt]));
}

function edgeFmaRows(fmt) {
  const values = EDGE_VALUES[fmt];
  const triples = [];
  values.forEach((a, i) => {
    values.forEach((b, j) => {
      triples.push([a, b, values[(i * 7 + j * 3) % values.length]]);
    });
  });
  return allModeRows(triples);
}

function generateEdgeVectors() {
  for (const spec of SPECS) {
    for (const [fmt, ops] of Object.entries(BINARY_OPS)) {
      const rows = edgeBinaryRows(fmt);
      for (const op of ops) {
        writeFixture(`edge_${fmt}`, spec, op, rows, { kind: "edge_binary", fmt });
      }
    }
    for (const [fmt, op] of Object.entries(FMA_OPS)) {
      writeFixture(`edge_${fmt}`, spec, op, edgeFmaRows(fmt), { kind: "edge_fma", fmt });
    }
    for (const [fmt, ops] of Object.entries(FLOAT_TO_INT_OPS)) {
      const rows = allRoundingRows(EDGE_VALUES[fmt].map((value) => [value]));
      for (const op of ops) {
        writeFixture(`edge_${fmt}`, spec, op, rows, { kind: "edge_unary_all_rounding", fmt });
      }
    }
    for (const [fmt, ops] of Object.entries(MIN_MAG_OPS)) {
      const rows = [];
      for (const exact of ["0", "1"]) {
        for (const value of EDGE_VALUES[fmt]) {
          rows.push(["near_even", "after", exact, [value]]);
        }
      }
      for (const op of ops) {
        writeFixture(`edge_${fmt}`, spec, op, rows, { kind: "edge_unary_min_mag", fmt });
      }
    }
    for (const [fmt, op] of Object.entries(ROUND_TO_INT_OPS)) {
      writeFixture(
        `edge_${fmt}`,
        spec,
        op,
        allRoundingRows(EDGE_VALUES[fmt].map((value) => [value])),
        { kind: "edge_unary_all_rounding", fmt },
      );
    }
    for (const [fmt, ops] of Object.entries(FLOAT_CONVERSION_OPS)) {
      const rows = allModeRows(EDGE_VALUES[fmt].map((value) => [value]));
      for (const op of ops) {
        writeFixture(`edge_${fmt}`, spec, op, rows, { kind: "edge_unary_all_mode", fmt });
      }
    }
    for (const [inputKind, op] of INT_TO_FLOAT_OPS) {
      const rows = allRoundingRows(INTEGER_INPUTS[inputKind].map((value) => [value]));
      writeFixture(`edge_${inputKind}`, spec, op, rows, { kind: "edge_int_all_rounding", inputKind });
    }
    for (const op of ["bf16_to_f32", "bf16_is_signaling_nan"]) {
      const rows = EDGE_VALUES.f16.map((value) => ["near_even", "after", "1", [value.slice(0, 4)]]);
      writeFixture("edge_bf16", spec, op, rows, { kind: "edge_bf16" });
    }
  }
}

function generateRandomVectors(args) {
  const rng = new Lcg(SEED);
  const counts = {
    f16: args.f16BinaryCount,
    f32: args.f32BinaryCount,
    f64: args.f64BinaryCount,
  };
  for (const spec of SPECS) {
    for (const [fmt, ops] of Object.entries(BINARY_OPS)) {
      for (const op of ops) {
        const seed = rng.state;
        writeFixture(
          `random_${fmt}`,
          spec,
          op,
          cycledRandomRows(rng, fmt, 2, counts[fmt]),
          { kind: "random", fmt, arity: 2, count: counts[fmt], seed },
        );
      }
    }
    for (const [fmt, op] of Object.entries(FMA_OPS)) {
      const seed = rng.state;
      writeFixture(
        `random_${fmt}`,
        spec,
        op,
        cycledRandomRows(rng, fmt, 3, args.fmaCount),
        { kind: "random", fmt, arity: 3, count: args.fmaCount, seed },
      );
    }
    const seed = rng.state;
    writeFixture(
      "random_f32",
      spec,
      "f32_to_bf16",
      cycledRandomRows(rng, "f32", 1, args.f32BinaryCount),
      { kind: "random", fmt: "f32", arity: 1, count: args.f32BinaryCount, seed },
    );
  }
}

function generateExhaustiveF16Vectors() {
  const rows = [];
  for (let value = 0; value < 0x10000; value += 1) {
    rows.push(["near_even", "after", "1", [value.toString(16).toUpperCase().padStart(4, "0")]]);
  }
  const roundRows = [];
  for (const rounding of ["near_even", "min", "max", "odd"]) {
    for (let value = 0; value < 0x10000; value += 1) {
      roundRows.push([rounding, "after", "1", [value.toString(16).toUpperCase().padStart(4, "0")]]);
    }
  }
  for (const spec of SPECS) {
    for (const op of ["f16_to_f32", "f16_to_f64", "f16_is_signaling_nan"]) {
      writeFixture("exhaustive_f16", spec, op, rows, { kind: "exhaustive_f16_unary" });
    }
    writeFixture(
      "exhaustive_f16",
      spec,
      "f16_round_to_int",
      roundRows,
      { kind: "exhaustive_f16_round_to_int" },
    );
  }
}

function generateExhaustiveBf16Vectors() {
  const rows = [];
  for (let value = 0; value < 0x10000; value += 1) {
    rows.push(["near_even", "after", "1", [value.toString(16).toUpperCase().padStart(4, "0")]]);
  }
  for (const spec of SPECS) {
    for (const op of ["bf16_to_f32", "bf16_is_signaling_nan"]) {
      writeFixture("exhaustive_bf16", spec, op, rows, { kind: "exhaustive_bf16_unary" });
    }
  }
}

function isPredicate(op) {
  return op.endsWith("_is_signaling_nan");
}

function isBoolResult(op) {
  return isPredicate(op)
    || op.endsWith("_eq")
    || op.endsWith("_le")
    || op.endsWith("_lt")
    || op.endsWith("_eq_signaling")
    || op.endsWith("_le_quiet")
    || op.endsWith("_lt_quiet");
}

function isFloatToInt(op) {
  return ["_to_ui32", "_to_ui64", "_to_i32", "_to_i64"].some((token) => op.includes(token))
    && !op.startsWith("ui")
    && !op.startsWith("i");
}

function needsRoundingArg(op) {
  return op.endsWith("_round_to_int") || (isFloatToInt(op) && !op.endsWith("_min_mag"));
}

function needsExactArg(op) {
  return needsRoundingArg(op) || op.endsWith("_min_mag");
}

function outputKind(op) {
  if (isBoolResult(op)) return "bool";
  if (op.endsWith("_to_ui32")) return "ui32";
  if (op.endsWith("_to_ui64")) return "ui64";
  if (op.endsWith("_to_i32")) return "i32";
  if (op.endsWith("_to_i64")) return "i64";
  if (op.endsWith("_to_ui32_min_mag")) return "ui32";
  if (op.endsWith("_to_ui64_min_mag")) return "ui64";
  if (op.endsWith("_to_i32_min_mag")) return "i32";
  if (op.endsWith("_to_i64_min_mag")) return "i64";
  if (op.endsWith("_to_bf16")) return "bf16";
  if (op.endsWith("_to_f16") || (op.endsWith("_round_to_int") && op.startsWith("f16_"))) return "f16";
  if (op.endsWith("_to_f32")) return "f32";
  if (op.endsWith("_to_f64")) return "f64";
  if (op.startsWith("f16_")) return "f16";
  if (op.startsWith("f32_")) return "f32";
  if (op.startsWith("f64_")) return "f64";
  fail(`unknown output kind for ${op}`);
}

function mbBitsType(fmt) {
  return {
    f16: "UInt16",
    bf16: "UInt16",
    f32: "UInt",
    f64: "UInt64",
    ui32: "UInt",
    i32: "UInt",
    ui64: "UInt64",
    i64: "UInt64",
  }[fmt];
}

function mbInputExpr(kind, value) {
  if (kind === "f16") return `F16::from_bits(${value})`;
  if (kind === "bf16") return `BF16::from_bits(${value})`;
  if (kind === "f32") return `F32::from_bits(${value})`;
  if (kind === "f64") return `F64::from_bits(${value})`;
  if (kind === "ui32") return value;
  if (kind === "ui64") return value;
  if (kind === "i32") return `${value}.reinterpret_as_int()`;
  if (kind === "i64") return `${value}.reinterpret_as_int64()`;
  fail(`unknown input kind ${kind}`);
}

function inputKindForUnaryOp(op, source) {
  if (source.kind === "edge_bf16") return "bf16";
  if (op.startsWith("bf16_")) return "bf16";
  if (Object.hasOwn(source, "inputKind")) return source.inputKind;
  if (Object.hasOwn(source, "input_kind")) return source.input_kind;
  return source.fmt ?? "f16";
}

function mbMixLines(op, inputExprs) {
  if (isPredicate(op)) {
    return [
      `    let value = ${op}(${inputExprs[0]})`,
      "    hash = sweep_mix(hash, if value { 1UL } else { 0UL })",
      "    hash = sweep_mix(hash, 0UL)",
    ];
  }

  let args;
  if (op.endsWith("_min_mag")) {
    args = ["context", inputExprs[0], "exact"];
  } else if (needsRoundingArg(op)) {
    args = ["context", inputExprs[0], "rounding", "exact"];
  } else {
    args = ["context", ...inputExprs];
  }

  const kind = outputKind(op);
  let valueExpr;
  if (kind === "bool") valueExpr = "if result.value { 1UL } else { 0UL }";
  else if (kind === "f16" || kind === "bf16") valueExpr = "result.value.to_bits().to_uint64()";
  else if (kind === "f32") valueExpr = "result.value.to_bits().to_uint64()";
  else if (kind === "f64") valueExpr = "result.value.to_bits()";
  else if (kind === "ui32") valueExpr = "result.value.to_uint64()";
  else if (kind === "ui64") valueExpr = "result.value";
  else if (kind === "i32") valueExpr = "result.value.reinterpret_as_uint().to_uint64()";
  else if (kind === "i64") valueExpr = "result.value.reinterpret_as_uint64()";
  else fail(`unknown output kind ${kind}`);

  return [
    `    let result = ${op}(${args.join(", ")})`,
    `    hash = sweep_mix(hash, ${valueExpr})`,
    "    hash = sweep_mix(hash, result.context.flags.to_bits().to_uint64())",
  ];
}

function mbCommonHelpers() {
  const lines = [
    "///|",
    "fn sweep_mix(hash : UInt64, value : UInt64) -> UInt64 {",
    `  (hash ^ value) * 0x${hex64(HASH_PRIME)}UL`,
    "}",
    "",
    "///|",
    "fn sweep_lcg_next(state : UInt64) -> UInt64 {",
    `  state * 0x${hex64(LCG_MULT)}UL + 0x${hex64(LCG_INC)}UL`,
    "}",
    "",
    "///|",
    "fn sweep_rounding4(index : Int) -> RoundingMode {",
    "  match index {",
    "    0 => NearEven",
    "    1 => Min",
    "    2 => Max",
    "    _ => Odd",
    "  }",
    "}",
    "",
    "///|",
    "fn sweep_rounding6(index : Int) -> RoundingMode {",
    "  match index {",
    "    0 => NearEven",
    "    1 => MinMag",
    "    2 => Min",
    "    3 => Max",
    "    4 => NearMaxMag",
    "    _ => Odd",
    "  }",
    "}",
    "",
    "///|",
    "fn sweep_tininess(index : Int) -> TininessMode {",
    "  if index == 0 { AfterRounding } else { BeforeRounding }",
    "}",
    "",
    "///|",
    "fn sweep_context(spec : Int, rounding : RoundingMode, tininess : TininessMode) -> Context {",
    "  let context = if spec == 0 { Context::default() } else { Context::riscv() }",
    "  context.with_rounding(rounding).with_tininess(tininess)",
    "}",
  ];

  for (const [fmt, values] of Object.entries(EDGE_VALUES)) {
    lines.push("", "///|", `fn sweep_edge_${fmt}(index : Int) -> ${mbBitsType(fmt)} {`, "  match index {");
    values.forEach((value, index) => {
      const suffix = fmt === "f16" ? "" : (fmt === "f32" ? "U" : "UL");
      lines.push(`    ${index} => 0x${value}${suffix}`);
    });
    lines.push("    _ => 0", "  }", "}");
  }

  for (const [kind, values] of Object.entries(INTEGER_INPUTS)) {
    lines.push("", "///|", `fn sweep_edge_${kind}(index : Int) -> ${mbBitsType(kind)} {`, "  match index {");
    const suffix = kind.endsWith("32") ? "U" : "UL";
    values.forEach((value, index) => {
      lines.push(`    ${index} => 0x${value}${suffix}`);
    });
    lines.push("    _ => 0", "  }", "}");
  }
  return lines;
}

function mbDefineRandomBits(lines, fmt, arity) {
  ["a", "b", "c"].slice(0, arity).forEach((name) => {
    lines.push("    rng = sweep_lcg_next(rng)");
    if (fmt === "f16") {
      lines.push(`    let ${name}_bits : UInt16 = (rng & 0xFFFFUL).to_uint16()`);
    } else if (fmt === "f32") {
      lines.push(`    let ${name}_bits : UInt = (rng & 0xFFFFFFFFUL).to_uint()`);
    } else {
      lines.push(`    let ${name}_bits : UInt64 = rng`);
    }
  });
}

function mbCaseLines(digestCase) {
  // This emitter rebuilds the input stream from compact source metadata. The
  // test compares only a digest, but the loop structure exactly mirrors the
  // fixture writer, including random seed advancement and edge-value ordering.
  const source = digestCase.source;
  const specId = digestCase.spec === "x86_8086_sse" ? 0 : 1;
  const fnName = `sweep_digest_${digestCase.name.replaceAll("-", "_")}`;
  const lines = ["", "///|", `fn ${fnName}() -> UInt64 {`, `  let mut hash = 0x${hex64(HASH_INIT)}UL`];
  const kind = String(source.kind);

  if (kind === "random") {
    const fmt = String(source.fmt);
    const arity = Number(source.arity);
    const count = Number(source.count);
    lines.push(`  let mut rng = 0x${hex64(source.seed)}UL`);
    lines.push(`  for index in 0..<${count} {`);
    lines.push("    let rounding = sweep_rounding4(index % 4)");
    lines.push("    let tininess = sweep_tininess((index / 4) % 2)");
    if (needsExactArg(digestCase.op)) lines.push("    let exact = true");
    if (!isPredicate(digestCase.op)) lines.push(`    let context = sweep_context(${specId}, rounding, tininess)`);
    mbDefineRandomBits(lines, fmt, arity);
    const inputs = ["a", "b", "c"].slice(0, arity).map((name) => mbInputExpr(fmt, `${name}_bits`));
    lines.push(...mbMixLines(digestCase.op, inputs));
    lines.push("  }");
  } else if (kind === "edge_binary" || kind === "edge_fma") {
    const fmt = String(source.fmt);
    const edgeLen = EDGE_VALUES[fmt].length;
    const arity = kind === "edge_binary" ? 2 : 3;
    const valueCount = edgeLen * edgeLen;
    const total = valueCount * ROUNDINGS.length * TININESS.length;
    lines.push(`  for index in 0..<${total} {`);
    lines.push(`    let mode_index = index / ${valueCount}`);
    lines.push(`    let input_index = index % ${valueCount}`);
    lines.push("    let rounding = sweep_rounding4(mode_index / 2)");
    lines.push("    let tininess = sweep_tininess(mode_index % 2)");
    lines.push(`    let context = sweep_context(${specId}, rounding, tininess)`);
    lines.push(`    let a_bits = sweep_edge_${fmt}(input_index / ${edgeLen})`);
    lines.push(`    let b_bits = sweep_edge_${fmt}(input_index % ${edgeLen})`);
    if (arity === 3) {
      lines.push(`    let c_bits = sweep_edge_${fmt}(((input_index / ${edgeLen}) * 7 + (input_index % ${edgeLen}) * 3) % ${edgeLen})`);
    }
    const inputs = ["a", "b", "c"].slice(0, arity).map((name) => mbInputExpr(fmt, `${name}_bits`));
    lines.push(...mbMixLines(digestCase.op, inputs));
    lines.push("  }");
  } else if (kind === "edge_unary_all_rounding" || kind === "edge_int_all_rounding") {
    const inputKind = inputKindForUnaryOp(digestCase.op, source);
    const count = Object.hasOwn(INTEGER_INPUTS, inputKind) ? INTEGER_INPUTS[inputKind].length : EDGE_VALUES[inputKind].length;
    const total = count * ALL_ROUNDINGS.length * 2;
    lines.push(`  for index in 0..<${total} {`);
    lines.push(`    let mode_index = index / ${count}`);
    lines.push(`    let input_index = index % ${count}`);
    lines.push("    let rounding = sweep_rounding6(mode_index / 2)");
    lines.push("    let tininess = AfterRounding");
    if (needsExactArg(digestCase.op)) lines.push("    let exact = mode_index % 2 == 1");
    if (!isPredicate(digestCase.op)) lines.push(`    let context = sweep_context(${specId}, rounding, tininess)`);
    lines.push(`    let a_bits = sweep_edge_${inputKind}(input_index)`);
    lines.push(...mbMixLines(digestCase.op, [mbInputExpr(inputKind, "a_bits")]));
    lines.push("  }");
  } else if (kind === "edge_unary_min_mag") {
    const fmt = String(source.fmt);
    const count = EDGE_VALUES[fmt].length;
    const total = count * 2;
    lines.push(`  for index in 0..<${total} {`);
    lines.push(`    let input_index = index % ${count}`);
    lines.push(`    let context = sweep_context(${specId}, NearEven, AfterRounding)`);
    lines.push(`    let exact = index / ${count} == 1`);
    lines.push(`    let a_bits = sweep_edge_${fmt}(input_index)`);
    lines.push(...mbMixLines(digestCase.op, [mbInputExpr(fmt, "a_bits")]));
    lines.push("  }");
  } else if (kind === "edge_unary_all_mode") {
    const fmt = String(source.fmt);
    const count = EDGE_VALUES[fmt].length;
    const total = count * ROUNDINGS.length * TININESS.length;
    lines.push(`  for index in 0..<${total} {`);
    lines.push(`    let mode_index = index / ${count}`);
    lines.push(`    let input_index = index % ${count}`);
    lines.push("    let rounding = sweep_rounding4(mode_index / 2)");
    lines.push("    let tininess = sweep_tininess(mode_index % 2)");
    lines.push(`    let context = sweep_context(${specId}, rounding, tininess)`);
    lines.push(`    let a_bits = sweep_edge_${fmt}(input_index)`);
    lines.push(...mbMixLines(digestCase.op, [mbInputExpr(fmt, "a_bits")]));
    lines.push("  }");
  } else if (kind === "edge_bf16") {
    const count = EDGE_VALUES.f16.length;
    lines.push(`  for index in 0..<${count} {`);
    if (!isPredicate(digestCase.op)) lines.push(`    let context = sweep_context(${specId}, NearEven, AfterRounding)`);
    lines.push("    let a_bits = sweep_edge_f16(index)");
    lines.push(...mbMixLines(digestCase.op, [mbInputExpr("bf16", "a_bits")]));
    lines.push("  }");
  } else if (kind === "exhaustive_f16_unary") {
    lines.push("  for index in 0..<0x10000 {");
    if (!isPredicate(digestCase.op)) lines.push(`    let context = sweep_context(${specId}, NearEven, AfterRounding)`);
    lines.push("    let a_bits = index.to_uint16()");
    lines.push(...mbMixLines(digestCase.op, [mbInputExpr("f16", "a_bits")]));
    lines.push("  }");
  } else if (kind === "exhaustive_bf16_unary") {
    lines.push("  for index in 0..<0x10000 {");
    if (!isPredicate(digestCase.op)) lines.push(`    let context = sweep_context(${specId}, NearEven, AfterRounding)`);
    lines.push("    let a_bits = index.to_uint16()");
    lines.push(...mbMixLines(digestCase.op, [mbInputExpr("bf16", "a_bits")]));
    lines.push("  }");
  } else if (kind === "exhaustive_f16_round_to_int") {
    lines.push("  for index in 0..<(0x10000 * 4) {");
    lines.push("    let rounding = sweep_rounding4(index / 0x10000)");
    lines.push(`    let context = sweep_context(${specId}, rounding, AfterRounding)`);
    lines.push("    let exact = true");
    lines.push("    let a_bits = (index % 0x10000).to_uint16()");
    lines.push(...mbMixLines(digestCase.op, [mbInputExpr("f16", "a_bits")]));
    lines.push("  }");
  } else {
    fail(`unknown sweep source kind ${kind}`);
  }

  lines.push(
    "  hash",
    "}",
    "",
    "///|",
    `test "golden sweep digest ${digestCase.name}" {`,
    `  @debug.assert_eq(${fnName}(), 0x${hex64(digestCase.digest)}UL)`,
    "}",
  );
  return lines;
}

function emitDigestTests() {
  const lines = [GENERATED_HEADER, ""];
  lines.push(...mbCommonHelpers());
  for (const digestCase of DIGEST_CASES) {
    lines.push(...mbCaseLines(digestCase));
  }
  writeText(SWEEP_TEST_PATH, lines.join("\n") + "\n");
}

function parseSweepArgs(argv) {
  const args = {
    quick: false,
    skipEdge: false,
    skipRandom: false,
    skipExhaustive: false,
    f16BinaryCount: 65536,
    f32BinaryCount: 10000,
    f64BinaryCount: 10000,
    fmaCount: 10000,
  };
  for (let index = 0; index < argv.length; index += 1) {
    const option = argv[index];
    if (option === "--quick") args.quick = true;
    else if (option === "--skip-edge") args.skipEdge = true;
    else if (option === "--skip-random") args.skipRandom = true;
    else if (option === "--skip-exhaustive") args.skipExhaustive = true;
    else if (option === "--f16-binary-count") args.f16BinaryCount = Number(argv[++index]);
    else if (option === "--f32-binary-count") args.f32BinaryCount = Number(argv[++index]);
    else if (option === "--f64-binary-count") args.f64BinaryCount = Number(argv[++index]);
    else if (option === "--fma-count") args.fmaCount = Number(argv[++index]);
    else fail(`unknown sweep option: ${option}`);
  }
  if (args.quick) {
    args.f16BinaryCount = 32;
    args.f32BinaryCount = 32;
    args.f64BinaryCount = 32;
    args.fmaCount = 32;
    args.skipExhaustive = true;
  }
  for (const [key, value] of Object.entries(args)) {
    if (key !== "quick" && key.startsWith("skip") === false && typeof value === "number" && !Number.isInteger(value)) {
      fail(`${key} must be an integer`);
    }
  }
  return args;
}

function generateSweepVectors(argv = [], { writePackages = true } = {}) {
  const args = parseSweepArgs(argv);
  ensureOracles();
  ensureDir(VECTOR_DIR);
  DIGEST_CASES.length = 0;
  cleanGeneratedSweepFixtures();
  if (!args.skipEdge) generateEdgeVectors();
  if (!args.skipRandom) generateRandomVectors(args);
  if (!args.skipExhaustive) {
    generateExhaustiveBf16Vectors();
    generateExhaustiveF16Vectors();
  }
  emitDigestTests();
  if (writePackages) generateVectorPackages();
  if (commandExists("wc")) {
    runCommand(["wc", "-l", ...listVectorFiles()], { stdio: "inherit" });
  }
}

function coreCases() {
  const cases = [];
  const add = (op, inputs, inputKinds, outputKind, rounding = "near_even", tininess = "after", exact = "1") => {
    cases.push(new CoreCase(op, rounding, tininess, exact, inputs, inputKinds, outputKind));
  };

  // Integer-to-float conversions.
  add("ui32_to_f16", ["00000001"], ["ui32"], "f16");
  add("ui32_to_f32", ["00000001"], ["ui32"], "f32");
  add("ui32_to_f64", ["00000001"], ["ui32"], "f64");
  add("ui64_to_f16", ["0000000000000001"], ["ui64"], "f16");
  add("ui64_to_f32", ["0000000000000001"], ["ui64"], "f32");
  add("ui64_to_f64", ["0000000000000001"], ["ui64"], "f64");
  add("i32_to_f16", ["FFFFFFFF"], ["i32"], "f16");
  add("i32_to_f32", ["FFFFFFFF"], ["i32"], "f32");
  add("i32_to_f64", ["FFFFFFFF"], ["i32"], "f64");
  add("i64_to_f16", ["FFFFFFFFFFFFFFFF"], ["i64"], "f16");
  add("i64_to_f32", ["FFFFFFFFFFFFFFFF"], ["i64"], "f32");
  add("i64_to_f64", ["FFFFFFFFFFFFFFFF"], ["i64"], "f64");

  // BF16.
  add("bf16_to_f32", ["3F80"], ["bf16"], "f32");
  add("f32_to_bf16", ["3F800000"], ["f32"], "bf16");
  add("bf16_is_signaling_nan", ["7F81"], ["bf16"], "bool");

  // F16.
  for (const [op, out] of [
    ["f16_to_ui32", "ui32"], ["f16_to_ui64", "ui64"],
    ["f16_to_i32", "i32"], ["f16_to_i64", "i64"],
    ["f16_to_ui32_min_mag", "ui32"], ["f16_to_ui64_min_mag", "ui64"],
    ["f16_to_i32_min_mag", "i32"], ["f16_to_i64_min_mag", "i64"],
  ]) {
    add(op, ["3E00"], ["f16"], out);
  }
  add("f16_to_f32", ["3C00"], ["f16"], "f32");
  add("f16_to_f64", ["3C00"], ["f16"], "f64");
  add("f16_round_to_int", ["3E00"], ["f16"], "f16");
  add("f16_add", ["3C00", "3C00"], ["f16", "f16"], "f16");
  add("f16_sub", ["4000", "3C00"], ["f16", "f16"], "f16");
  add("f16_mul", ["3C00", "4000"], ["f16", "f16"], "f16");
  add("f16_mul_add", ["4000", "4200", "3C00"], ["f16", "f16", "f16"], "f16");
  add("f16_div", ["3C00", "4000"], ["f16", "f16"], "f16");
  add("f16_rem", ["4500", "4000"], ["f16", "f16"], "f16");
  add("f16_sqrt", ["4000"], ["f16"], "f16");
  add("f16_eq", ["8000", "0000"], ["f16", "f16"], "bool");
  add("f16_le", ["3C00", "4000"], ["f16", "f16"], "bool");
  add("f16_lt", ["3C00", "4000"], ["f16", "f16"], "bool");
  add("f16_eq_signaling", ["7E00", "3C00"], ["f16", "f16"], "bool");
  add("f16_le_quiet", ["7C01", "3C00"], ["f16", "f16"], "bool");
  add("f16_lt_quiet", ["7C01", "3C00"], ["f16", "f16"], "bool");
  add("f16_is_signaling_nan", ["7C01"], ["f16"], "bool");

  // F32.
  for (const [op, out] of [
    ["f32_to_ui32", "ui32"], ["f32_to_ui64", "ui64"],
    ["f32_to_i32", "i32"], ["f32_to_i64", "i64"],
    ["f32_to_ui32_min_mag", "ui32"], ["f32_to_ui64_min_mag", "ui64"],
    ["f32_to_i32_min_mag", "i32"], ["f32_to_i64_min_mag", "i64"],
  ]) {
    add(op, ["3FC00000"], ["f32"], out);
  }
  add("f32_to_f16", ["3F800000"], ["f32"], "f16");
  add("f32_to_f64", ["3F800000"], ["f32"], "f64");
  add("f32_round_to_int", ["3FC00000"], ["f32"], "f32");
  add("f32_add", ["3F800000", "3F800000"], ["f32", "f32"], "f32");
  add("f32_sub", ["40000000", "3F800000"], ["f32", "f32"], "f32");
  add("f32_mul", ["3F800000", "40000000"], ["f32", "f32"], "f32");
  add("f32_mul_add", ["40000000", "40400000", "3F800000"], ["f32", "f32", "f32"], "f32");
  add("f32_div", ["3F800000", "40400000"], ["f32", "f32"], "f32");
  add("f32_rem", ["40A00000", "40000000"], ["f32", "f32"], "f32");
  add("f32_sqrt", ["40000000"], ["f32"], "f32");
  add("f32_eq", ["80000000", "00000000"], ["f32", "f32"], "bool");
  add("f32_le", ["3F800000", "40000000"], ["f32", "f32"], "bool");
  add("f32_lt", ["3F800000", "40000000"], ["f32", "f32"], "bool");
  add("f32_eq_signaling", ["7FC00000", "3F800000"], ["f32", "f32"], "bool");
  add("f32_le_quiet", ["7F800001", "3F800000"], ["f32", "f32"], "bool");
  add("f32_lt_quiet", ["7F800001", "3F800000"], ["f32", "f32"], "bool");
  add("f32_is_signaling_nan", ["7F800001"], ["f32"], "bool");

  // F64.
  for (const [op, out] of [
    ["f64_to_ui32", "ui32"], ["f64_to_ui64", "ui64"],
    ["f64_to_i32", "i32"], ["f64_to_i64", "i64"],
    ["f64_to_ui32_min_mag", "ui32"], ["f64_to_ui64_min_mag", "ui64"],
    ["f64_to_i32_min_mag", "i32"], ["f64_to_i64_min_mag", "i64"],
  ]) {
    add(op, ["3FF8000000000000"], ["f64"], out);
  }
  add("f64_to_f16", ["3FF0000000000000"], ["f64"], "f16");
  add("f64_to_f32", ["3FF0000000000000"], ["f64"], "f32");
  add("f64_round_to_int", ["3FF8000000000000"], ["f64"], "f64");
  add("f64_add", ["3FF0000000000000", "3FF0000000000000"], ["f64", "f64"], "f64");
  add("f64_sub", ["4000000000000000", "3FF0000000000000"], ["f64", "f64"], "f64");
  add("f64_mul", ["3FF0000000000000", "4000000000000000"], ["f64", "f64"], "f64");
  add("f64_mul_add", ["4000000000000000", "4008000000000000", "3FF0000000000000"], ["f64", "f64", "f64"], "f64");
  add("f64_div", ["3FF0000000000000", "4008000000000000"], ["f64", "f64"], "f64");
  add("f64_rem", ["4014000000000000", "4000000000000000"], ["f64", "f64"], "f64");
  add("f64_sqrt", ["4000000000000000"], ["f64"], "f64");
  add("f64_eq", ["8000000000000000", "0000000000000000"], ["f64", "f64"], "bool");
  add("f64_le", ["3FF0000000000000", "4000000000000000"], ["f64", "f64"], "bool");
  add("f64_lt", ["3FF0000000000000", "4000000000000000"], ["f64", "f64"], "bool");
  add("f64_eq_signaling", ["7FF8000000000000", "3FF0000000000000"], ["f64", "f64"], "bool");
  add("f64_le_quiet", ["7FF0000000000001", "3FF0000000000000"], ["f64", "f64"], "bool");
  add("f64_lt_quiet", ["7FF0000000000001", "3FF0000000000000"], ["f64", "f64"], "bool");
  add("f64_is_signaling_nan", ["7FF0000000000001"], ["f64"], "bool");

  return cases;
}

function runOracle(spec, coreCase) {
  ensureOracles();
  const args = [oraclePath(spec), coreCase.op, coreCase.rounding, coreCase.tininess, coreCase.exact, ...coreCase.inputs];
  return runCommand(args).stdout.trim();
}

function mbRounding(name) {
  return {
    near_even: "NearEven",
    min_mag: "MinMag",
    min: "Min",
    max: "Max",
    near_max_mag: "NearMaxMag",
    odd: "Odd",
  }[name];
}

function mbTininess(name) {
  return { before: "BeforeRounding", after: "AfterRounding" }[name];
}

function mbContext(spec, rounding, tininess) {
  const base = spec === "x86_8086_sse" ? "Context::default()" : "Context::riscv()";
  return `${base}.with_rounding(${mbRounding(rounding)}).with_tininess(${mbTininess(tininess)})`;
}

function mbInput(kind, value, qualified = false) {
  const prefix = qualified ? "@sf." : "";
  if (kind === "f16") return `${prefix}F16::from_bits(0x${value})`;
  if (kind === "bf16") return `${prefix}BF16::from_bits(0x${value})`;
  if (kind === "f32") return `${prefix}F32::from_bits(0x${value}U)`;
  if (kind === "f64") return `${prefix}F64::from_bits(0x${value}UL)`;
  if (kind === "ui32") return `0x${value}U`;
  if (kind === "ui64") return `0x${value}UL`;
  if (kind === "i32") return `0x${value}U.reinterpret_as_int()`;
  if (kind === "i64") return `0x${value}UL.reinterpret_as_int64()`;
  fail(`unknown input kind ${kind}`);
}

function mbExpected(kind, value) {
  if (kind === "f16" || kind === "bf16") return `0x${value}`;
  if (kind === "f32") return `0x${value}U`;
  if (kind === "f64") return `0x${value}UL`;
  if (kind === "ui32") return `0x${value}U`;
  if (kind === "ui64") return `0x${value}UL`;
  if (kind === "i32") return `0x${value}U.reinterpret_as_int()`;
  if (kind === "i64") return `0x${value}UL.reinterpret_as_int64()`;
  if (kind === "bool") return value === "1" ? "true" : "false";
  fail(`unknown expected kind ${kind}`);
}

function coreCallExpr(coreCase, spec) {
  const context = mbContext(spec, coreCase.rounding, coreCase.tininess);
  const inputs = coreCase.inputKinds.map((kind, index) => mbInput(kind, coreCase.inputs[index]));
  const exact = coreCase.exact === "1" ? "true" : "false";
  const op = coreCase.op;

  if (op.endsWith("_is_signaling_nan")) return `${op}(${inputs[0]})`;
  if (op.endsWith("_round_to_int")) {
    return `${op}(${context}, ${inputs[0]}, ${mbRounding(coreCase.rounding)}, ${exact})`;
  }
  if (op.includes("_to_")
    && (op.endsWith("ui32") || op.endsWith("ui64") || op.endsWith("i32") || op.endsWith("i64"))) {
    return `${op}(${context}, ${inputs[0]}, ${mbRounding(coreCase.rounding)}, ${exact})`;
  }
  if (op.endsWith("_min_mag")) return `${op}(${context}, ${inputs[0]}, ${exact})`;
  return `${op}(${context}, ${inputs.join(", ")})`;
}

function emitCoreTest(records) {
  const lines = [
    "///|",
    'test "golden core vectors match committed C oracle records" {',
  ];
  records.forEach(([coreCase, record], index) => {
    const fields = record.split(/\s+/);
    const spec = fields[0];
    const output = fields.at(-2);
    const flags = fields.at(-1);
    const expr = coreCallExpr(coreCase, spec);
    lines.push(`  // ${record}`);
    lines.push(`  let result${index} = ${expr}`);
    if (coreCase.outputKind === "bool" && coreCase.op.endsWith("_is_signaling_nan")) {
      lines.push(`  @debug.assert_eq(result${index}, ${mbExpected(coreCase.outputKind, output)})`);
      lines.push(`  @debug.assert_eq(0U, 0x${flags}U)`);
    } else {
      const valueExpr = ["f16", "bf16", "f32", "f64"].includes(coreCase.outputKind)
        ? `result${index}.value.to_bits()`
        : `result${index}.value`;
      lines.push(`  @debug.assert_eq(${valueExpr}, ${mbExpected(coreCase.outputKind, output)})`);
      lines.push(`  @debug.assert_eq(result${index}.context.flags.to_bits(), 0x${flags}U)`);
    }
  });
  lines.push("}");
  return `${lines.join("\n")}\n`;
}

function generateCoreVectors({ writePackages = true } = {}) {
  const records = [];
  for (const coreCase of coreCases()) {
    for (const spec of SPECS) {
      records.push([coreCase, runOracle(spec, coreCase)]);
    }
  }
  writeText(CORE_VECTOR_PATH, records.map(([, record]) => record).join("\n") + "\n");
  writeText(CORE_TEST_PATH, emitCoreTest(records));
  if (writePackages) generateVectorPackages();
}

function allOps() {
  const ops = new Set();
  for (const group of Object.values(BINARY_OPS)) group.forEach((op) => ops.add(op));
  Object.values(FMA_OPS).forEach((op) => ops.add(op));
  Object.values(ROUND_TO_INT_OPS).forEach((op) => ops.add(op));
  for (const group of Object.values(FLOAT_TO_INT_OPS)) group.forEach((op) => ops.add(op));
  for (const group of Object.values(MIN_MAG_OPS)) group.forEach((op) => ops.add(op));
  for (const group of Object.values(FLOAT_CONVERSION_OPS)) group.forEach((op) => ops.add(op));
  INT_TO_FLOAT_OPS.forEach(([, op]) => ops.add(op));
  ops.add("bf16_to_f32");
  ops.add("bf16_is_signaling_nan");
  for (const fmt of ["f16", "f32", "f64"]) {
    [
      `${fmt}_sqrt`,
      `${fmt}_eq`,
      `${fmt}_le`,
      `${fmt}_lt`,
      `${fmt}_eq_signaling`,
      `${fmt}_le_quiet`,
      `${fmt}_lt_quiet`,
      `${fmt}_is_signaling_nan`,
    ].forEach((op) => ops.add(op));
  }
  return ops;
}

const OP_RE = new RegExp(`\\b(${[...allOps()].sort((a, b) => b.length - a.length).map(escapeRegex).join("|")})\\(`, "g");

function escapeRegex(text) {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function lineCounts() {
  const counts = {};
  for (const file of listVectorFiles()) {
    const content = readText(file);
    counts[stem(file)] = content.length === 0 ? 0 : content.split(/\r?\n/).filter((line, index, lines) => index < lines.length - 1 || line.length > 0).length;
  }
  return counts;
}

function addSource(sources, prefix, spec, op, source) {
  sources[`${prefix}_${op}_${spec}`] = [op, source];
}

function advanceLcg(rng, count, arity) {
  for (let index = 0; index < count * arity; index += 1) {
    rng.next();
  }
}

function expectedSweepSources(counts) {
  // Package generation works from committed text fixtures. This reconstructs
  // enough source metadata from fixture names and line counts to emit range
  // digest functions without regenerating the fixture files themselves.
  const sources = {};
  for (const spec of SPECS) {
    for (const [fmt, ops] of Object.entries(BINARY_OPS)) {
      for (const op of ops) addSource(sources, `edge_${fmt}`, spec, op, { kind: "edge_binary", fmt });
    }
    for (const [fmt, op] of Object.entries(FMA_OPS)) {
      addSource(sources, `edge_${fmt}`, spec, op, { kind: "edge_fma", fmt });
    }
    for (const [fmt, ops] of Object.entries(FLOAT_TO_INT_OPS)) {
      for (const op of ops) addSource(sources, `edge_${fmt}`, spec, op, { kind: "edge_unary_all_rounding", fmt });
    }
    for (const [fmt, ops] of Object.entries(MIN_MAG_OPS)) {
      for (const op of ops) addSource(sources, `edge_${fmt}`, spec, op, { kind: "edge_unary_min_mag", fmt });
    }
    for (const [fmt, op] of Object.entries(ROUND_TO_INT_OPS)) {
      addSource(sources, `edge_${fmt}`, spec, op, { kind: "edge_unary_all_rounding", fmt });
    }
    for (const [fmt, ops] of Object.entries(FLOAT_CONVERSION_OPS)) {
      for (const op of ops) addSource(sources, `edge_${fmt}`, spec, op, { kind: "edge_unary_all_mode", fmt });
    }
    for (const [inputKind, op] of INT_TO_FLOAT_OPS) {
      addSource(sources, `edge_${inputKind}`, spec, op, { kind: "edge_int_all_rounding", inputKind });
    }
    for (const op of ["bf16_to_f32", "bf16_is_signaling_nan"]) {
      addSource(sources, "edge_bf16", spec, op, { kind: "edge_bf16" });
    }
  }

  const rng = new Lcg(SEED);
  const defaultCounts = { f16: 65536, f32: 10000, f64: 10000 };
  for (const spec of SPECS) {
    for (const [fmt, ops] of Object.entries(BINARY_OPS)) {
      for (const op of ops) {
        const name = `random_${fmt}_${op}_${spec}`;
        const count = counts[name] ?? defaultCounts[fmt];
        if (Object.hasOwn(counts, name)) {
          addSource(sources, `random_${fmt}`, spec, op, { kind: "random", fmt, arity: 2, count, seed: rng.state });
        }
        advanceLcg(rng, count, 2);
      }
    }
    for (const [fmt, op] of Object.entries(FMA_OPS)) {
      const name = `random_${fmt}_${op}_${spec}`;
      const count = counts[name] ?? 10000;
      if (Object.hasOwn(counts, name)) {
        addSource(sources, `random_${fmt}`, spec, op, { kind: "random", fmt, arity: 3, count, seed: rng.state });
      }
      advanceLcg(rng, count, 3);
    }
    const name = `random_f32_f32_to_bf16_${spec}`;
    const count = counts[name] ?? 10000;
    if (Object.hasOwn(counts, name)) {
      addSource(sources, "random_f32", spec, "f32_to_bf16", { kind: "random", fmt: "f32", arity: 1, count, seed: rng.state });
    }
    advanceLcg(rng, count, 1);
  }

  for (const spec of SPECS) {
    for (const op of ["bf16_to_f32", "bf16_is_signaling_nan"]) {
      addSource(sources, "exhaustive_bf16", spec, op, { kind: "exhaustive_bf16_unary" });
    }
    for (const op of ["f16_to_f32", "f16_to_f64", "f16_is_signaling_nan"]) {
      addSource(sources, "exhaustive_f16", spec, op, { kind: "exhaustive_f16_unary" });
    }
    addSource(sources, "exhaustive_f16", spec, "f16_round_to_int", { kind: "exhaustive_f16_round_to_int" });
  }
  return sources;
}

function qualifyLine(line) {
  let output = line;
  output = output.replaceAll("Context::", "@sf.Context::");
  output = output.replaceAll("BF16::", "__MBT_BF16_METHOD__");
  output = output.replaceAll("F16::", "@sf.F16::");
  output = output.replaceAll("__MBT_BF16_METHOD__", "@sf.BF16::");
  output = output.replaceAll("F32::", "@sf.F32::");
  output = output.replaceAll("F64::", "@sf.F64::");
  output = output.replaceAll("RoundingMode", "@sf.RoundingMode");
  output = output.replaceAll("TininessMode", "@sf.TininessMode");
  output = output.replaceAll(") -> Context", ") -> @sf.Context");
  output = output.replace(VARIANT_RE, (_, name) => `@sf.RoundingMode::${name}`);
  output = output.replace(TININESS_RE, (_, name) => `@sf.TininessMode::${name}`);
  output = output.replace(OP_RE, (_, op) => `@sf.${op}(`);
  return output;
}

function qualify(lines) {
  return lines.map((line) => qualifyLine(line));
}

function publicTestHelpers(lines) {
  return lines.map((line) => line.startsWith("fn sweep_") ? line.replace("fn sweep_", "pub fn sweep_") : line);
}

function readRecords(file) {
  return readText(file)
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0);
}

function inputKinds(op) {
  if (op.startsWith("ui32_to_")) return ["ui32"];
  if (op.startsWith("ui64_to_")) return ["ui64"];
  if (op.startsWith("i32_to_")) return ["i32"];
  if (op.startsWith("i64_to_")) return ["i64"];
  if (op.startsWith("bf16_")) return ["bf16"];
  const fmt = op.slice(0, 3);
  if (op.endsWith("_mul_add")) return [fmt, fmt, fmt];
  if (op.endsWith("_add")
    || op.endsWith("_sub")
    || op.endsWith("_mul")
    || op.endsWith("_div")
    || op.endsWith("_rem")
    || (isBoolResult(op) && !isPredicate(op))) {
    return [fmt, fmt];
  }
  return [fmt];
}

function directCall(op, spec, rounding, tininess, exact, inputs) {
  const context = `sweep_context(${spec === "x86_8086_sse" ? 0 : 1}, ${ROUNDING[rounding]}, ${TININESS_MODE[tininess]})`;
  const exactValue = exact === "1" ? "true" : "false";
  if (isPredicate(op)) return `@sf.${op}(${inputs[0]})`;
  if (op.endsWith("_min_mag")) return `@sf.${op}(${context}, ${inputs[0]}, ${exactValue})`;
  if (needsRoundingArg(op)) return `@sf.${op}(${context}, ${inputs[0]}, ${ROUNDING[rounding]}, ${exactValue})`;
  return `@sf.${op}(${context}, ${inputs.join(", ")})`;
}

function directRecordTest(file) {
  const records = readRecords(file);
  const lines = [
    "",
    "///|",
    `test "golden vector records ${stem(file)}" {`,
  ];
  records.forEach((record, index) => {
    const fields = record.split(/\s+/);
    const [spec, op, rounding, tininess, exact] = fields.slice(0, 5);
    const kinds = inputKinds(op);
    const rawInputs = fields.slice(5, 5 + kinds.length);
    const output = fields.at(-2);
    const flags = fields.at(-1);
    const inputs = kinds.map((kind, i) => mbInput(kind, rawInputs[i], true));
    const expr = directCall(op, spec, rounding, tininess, exact, inputs);
    const kind = outputKind(op);
    lines.push(`  // ${record}`);
    lines.push(`  let result${index} = ${expr}`);
    if (isPredicate(op)) {
      lines.push(`  @debug.assert_eq(result${index}, ${mbExpected(kind, output)})`);
      lines.push(`  @debug.assert_eq(0U, 0x${flags}U)`);
    } else if (kind === "bool") {
      lines.push(`  @debug.assert_eq(result${index}.value, ${mbExpected(kind, output)})`);
      lines.push(`  @debug.assert_eq(result${index}.context.flags.to_bits(), 0x${flags}U)`);
    } else if (["f16", "bf16", "f32", "f64"].includes(kind)) {
      lines.push(`  @debug.assert_eq(result${index}.value.to_bits(), ${mbExpected(kind, output)})`);
      lines.push(`  @debug.assert_eq(result${index}.context.flags.to_bits(), 0x${flags}U)`);
    } else {
      lines.push(`  @debug.assert_eq(result${index}.value, ${mbExpected(kind, output)})`);
      lines.push(`  @debug.assert_eq(result${index}.context.flags.to_bits(), 0x${flags}U)`);
    }
  });
  lines.push("}");
  return new GeneratedTest(null, lines);
}

function sweepFunctionName(file) {
  return `sweep_digest_${stem(file).replaceAll("-", "_")}`;
}

function sweepRangeFunction(file, source) {
  const [op, sourceInfo] = source;
  const records = readRecords(file);
  const digestCase = new DigestCase({
    name: stem(file),
    spec: stem(file).endsWith("_x86_8086_sse") ? "x86_8086_sse" : "riscv",
    op,
    source: sourceInfo,
    digest: digestRecords(records),
  });
  const fnName = sweepFunctionName(file);
  const rangeFnName = `${fnName}_range`;
  const fullLines = qualify(mbCaseLines(digestCase));
  const testIndex = fullLines.findIndex((line) => line.startsWith("test "));
  const functionLines = fullLines.slice(0, testIndex - 1);
  const output = [];
  let insertedRandomSkip = false;
  for (const line of functionLines) {
    if (line === `fn ${fnName}() -> UInt64 {`) {
      output.push(`fn ${rangeFnName}(start : Int, end : Int) -> UInt64 {`);
    } else if (line.startsWith("  for index in 0..<")) {
      if (sourceInfo.kind === "random" && !insertedRandomSkip) {
        const arity = Number(sourceInfo.arity);
        output.push(`  for _ in 0..<(start * ${arity}) {`);
        output.push("    rng = sweep_lcg_next(rng)");
        output.push("  }");
        insertedRandomSkip = true;
      }
      output.push("  for index in start..<end {");
    } else {
      output.push(line);
    }
  }
  return output;
}

function sweepDigestTests(file, source) {
  const records = readRecords(file);
  const fnName = sweepFunctionName(file);
  const tests = [];
  for (let chunkIndex = 0, start = 0; start < records.length; chunkIndex += 1, start += DIGEST_CHUNK_SIZE) {
    const end = Math.min(start + DIGEST_CHUNK_SIZE, records.length);
    const digest = digestRecords(records.slice(start, end));
    const lines = [
      "",
      "///|",
      `test "golden sweep digest ${stem(file)} chunk ${chunkIndex}" {`,
      "  @debug.assert_eq(",
      `    ${fnName}_range(${start}, ${end}),`,
      `    0x${hex64(digest)}UL,`,
      "  )",
      "}",
    ];
    tests.push(new GeneratedTest(fnName, lines));
  }
  return [fnName, tests];
}

function moonPkg() {
  return [
    "import {",
    '  "myfreess/softfloat" @sf,',
    '  "moonbitlang/core/debug",',
    '} for "test"',
    "",
  ].join("\n");
}

function cleanBatches() {
  ensureDir(TEST_ROOT);
  for (const name of fs.readdirSync(TEST_ROOT)) {
    const file = path.join(TEST_ROOT, name);
    if (name.startsWith("batch") && fs.statSync(file).isDirectory()) {
      fs.rmSync(file, { recursive: true, force: true });
    }
  }
}

function writeBatches(blocks, helpers) {
  cleanBatches();
  const batchCount = Math.ceil(blocks.length / TESTS_PER_BATCH);
  for (let batchIndex = 0; batchIndex < batchCount; batchIndex += 1) {
    const batchDir = path.join(TEST_ROOT, `batch${batchIndex}`);
    ensureDir(batchDir);
    writeText(path.join(batchDir, "moon.pkg"), moonPkg());

    const batchBlocks = blocks.slice(batchIndex * TESTS_PER_BATCH, (batchIndex + 1) * TESTS_PER_BATCH);
    const helperLines = [GENERATED_HEADER, ""];
    helperLines.push(...publicTestHelpers(qualify(mbCommonHelpers())));
    const seenHelpers = new Set();
    for (const block of batchBlocks) {
      if (block.helper !== null && !seenHelpers.has(block.helper)) {
        helperLines.push(...helpers[block.helper]);
        seenHelpers.add(block.helper);
      }
    }
    writeText(path.join(batchDir, "helpers_test.mbt"), helperLines.join("\n").trimEnd() + "\n");

    const fileCount = Math.ceil(batchBlocks.length / TESTS_PER_FILE);
    for (let fileIndex = 0; fileIndex < fileCount; fileIndex += 1) {
      const fileBlocks = batchBlocks.slice(fileIndex * TESTS_PER_FILE, (fileIndex + 1) * TESTS_PER_FILE);
      const lines = [GENERATED_HEADER];
      for (const block of fileBlocks) {
        lines.push(...block.block);
      }
      writeText(path.join(batchDir, `vectors_${String(fileIndex).padStart(3, "0")}_test.mbt`), lines.join("\n").trimEnd() + "\n");
    }
  }
}

function generateVectorPackages() {
  const counts = lineCounts();
  const sources = expectedSweepSources(counts);
  const blocks = [];
  const helpers = {};
  for (const name of ["core", "smoke"]) {
    const file = path.join(VECTOR_DIR, `${name}.txt`);
    if (exists(file)) {
      blocks.push(directRecordTest(file));
    }
  }
  for (const file of listVectorFiles()) {
    const name = stem(file);
    if (name === "core" || name === "smoke") continue;
    const source = sources[name];
    if (source === undefined) {
      fail(`no generated sweep source metadata for ${path.basename(file)}`);
    }
    const [helperName, tests] = sweepDigestTests(file, source);
    helpers[helperName] = sweepRangeFunction(file, source);
    blocks.push(...tests);
  }
  writeBatches(blocks, helpers);
}

function checkVectorGroups() {
  ensureOracles();
  const groups = new Map();
  for (const file of listVectorFiles()) {
    const lines = readText(file).split(/\r?\n/);
    lines.forEach((rawLine, offset) => {
      const line = rawLine.trim();
      if (line.length === 0 || line.startsWith("#")) return;
      const fields = line.split(/\s+/);
      if (fields.length < 7) {
        fail(`${file}:${offset + 1}: malformed vector record`);
      }
      const [spec, op, rounding, tininess, exact] = fields.slice(0, 5);
      if (!Object.hasOwn(ORACLES, spec)) {
        fail(`${file}:${offset + 1}: unknown specialization ${spec}`);
      }
      const key = `${spec}\0${op}\0${rounding}\0${tininess}\0${exact}`;
      if (!groups.has(key)) {
        groups.set(key, []);
      }
      groups.get(key).push({
        file,
        lineNumber: offset + 1,
        line,
        inputs: fields.slice(5, -2),
      });
    });
  }

  for (const key of [...groups.keys()].sort()) {
    const [spec, op, rounding, tininess, exact] = key.split("\0");
    const records = groups.get(key);
    const input = records.map((record) => record.inputs.join(" ")).join("\n") + "\n";
    const completed = runCommand(
      [oraclePath(spec), "--batch", op, rounding, tininess, exact],
      { input, captureOutput: true },
    );
    const actualLines = completed.stdout.split(/\r?\n/).filter((line) => line.length > 0);
    if (actualLines.length !== records.length) {
      fail(`${op}/${spec}: expected ${records.length} records, got ${actualLines.length}`);
    }
    records.forEach((record, index) => {
      const actual = actualLines[index];
      if (actual !== record.line) {
        fail([
          `vector mismatch in ${record.file}:${record.lineNumber}`,
          `expected: ${record.line}`,
          `actual:   ${actual}`,
        ].join("\n"));
      }
    });
  }
}

function commandExists(command) {
  const result = spawnSync("command", ["-v", command], { shell: true, encoding: "utf8" });
  return result.status === 0;
}

function printHelp() {
  process.stdout.write(`Usage: tools/test_gen.mjs <command> [options]

Commands:
  core       Generate tools/vectors/core.txt and golden_core_wbtest.mbt, then rebuild sweep_test.
  sweep      Generate edge/random/exhaustive vectors and golden_sweep_digest_wbtest.mbt, then rebuild sweep_test.
  packages   Rebuild sweep_test/batch<N> packages from existing tools/vectors fixtures.
  check      Replay all committed fixtures through the local C oracle binaries.
  all        Generate core and sweep fixtures, then rebuild sweep_test once.

Sweep options:
  --quick
  --skip-edge
  --skip-random
  --skip-exhaustive
  --f16-binary-count <n>
  --f32-binary-count <n>
  --f64-binary-count <n>
  --fma-count <n>
`);
}

function main(argv) {
  const [command, ...rest] = argv;
  if (command === "core") {
    generateCoreVectors();
  } else if (command === "sweep") {
    generateSweepVectors(rest);
  } else if (command === "packages") {
    generateVectorPackages();
  } else if (command === "check") {
    checkVectorGroups();
  } else if (command === "all") {
    generateCoreVectors({ writePackages: false });
    generateSweepVectors(rest, { writePackages: false });
    generateVectorPackages();
  } else if (command === undefined || command === "-h" || command === "--help" || command === "help") {
    printHelp();
  } else {
    printHelp();
    fail(`unknown command: ${command}`);
  }
}

try {
  main(process.argv.slice(2));
} catch (error) {
  process.stderr.write(`${error.message}\n`);
  process.exit(1);
}
